use_frameworks!

target 'JKLocationMananger_Example' do
  pod 'JKLocationMananger', :path => '../'

  target 'JKLocationMananger_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
